# Generated by Django 3.2.5 on 2021-08-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='umeasurement_unit',
            new_name='measurement_unit',
        ),
    ]
