# Generated by Django 3.2.5 on 2021-08-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='value',
            new_name='amount',
        ),
    ]
